[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
line-length = 88
select = ["E", "F", "I"]
ignore = []
target-version = "py311"
exclude = ["data", "index", "scripts/viz_report.py"]

[tool.ruff.isort]
combine-as-imports = true
lines-between-types = 1

[tool.ruff.per-file-ignores]
"app/demo_ui.py" = ["E402"]
